language: python
python:
  - 2.6
  - 2.7
env:
  - TARGET=test
  - TARGET=coverage.sh
  - TARGET=python-validation.sh
install:
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py
  - bin/buildout -N -t 3
script: bin/$TARGET
